calendar_calendar_list:
  pattern: /calendars
  defaults: { _controller: calendar.controller.calendar:listAction }

#calendar_calendar_add:
#  pattern: /calendar/:id/add
#  defaults: { _controller: calendar.controller.calendar:addAction }
#  requirements: { id: "[\w\-]{8}", _method: "get" }